# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GooglePlacesDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GooglePlacesDemo
pod 'GooglePlaces', '~> 2.1'
pod 'AsyncDisplayKit', '2.0-beta.1'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'Mixpanel-swift', '~> 2.1'
end
